### Site title
remote_theme: jitinnair1/gradfolio

title: Erivan INAN
description: Master's Student in Data Science | Sorbonne Université | ISUP

# Base URL and Repository Name
baseurl: ""  # Laisser vide car c'est un site GitHub Pages avec un nom de repo correspondant
url: "https://erivaninan.github.io"  # Ton site GitHub Pages

# Contact email
email: inanerivan@gmail.com

# Pagination for blog posts
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links (ajoute les tiens si nécessaire)
linkedin: "https://www.linkedin.com/in/erivan-inan/"
github: "https://github.com/erivaninan/"

# Markdown Configuration
highlighter: rouge
markdown: kramdown

# Jekyll Plugins (Important pour que le thème fonctionne)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-collections  # Ajout pour bien gérer les collections

# Optimisation HTML
compress_html:
  clippings: [html, div, p, ul, td, h1, h2, h3, h4, link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collections (Projets et Formations affichés sur ton site)
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md
  formations:
    output: true
    permalink: /formation/:name/

collections_dir: _collections  # S'assurer que les collections sont bien chargées

# SCSS / CSS
sass:
  sass_dir: assets/css/_sass
  style: compressed

# Inclure certains dossiers pour Jekyll
include:
  - _pages
  - _formations  # Ajout pour s'assurer que Jekyll génère bien les formations

# Exclure certains fichiers inutiles pour la génération du site
exclude:
  - README.md
  - LICENSE.md
